defaults:
  - hydra: default

wandb:
  use_wandb: True
  project: neural-net-template
  entity: jlko

experiment:
  random_seed: -1
  dtype: half # half, float, double

dataset:
  _target_: neural.datasets.CIFAR10 # CIFAR10, FashionMNIST
  cfg:
    val_size: 5000
    train_batch_size: 128
    test_batch_size: 1024

trainer:
  max_epochs: 30
  early_stopping_epochs: 10
  scheduler: cosine
  loss: crossentropy
  custom_L2_loss: False
  optimizer:
    name: sgd
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 0.0005

model:
  _target_: neural.models.ResNet18Tweaked # ResNet18, ResNet18Tweaked, Mobilenetv3
  cfg:
