name: neural
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - pip
  - pip:
    - laplace-torch
    - wandb
    - scikit-learn
    - pandas
    - pycodestyle
    - hydra-core
    - omegaconf
    - jupyterlab
    - notebook
    - matplotlib
    - seaborn
    - tqdm
    - ipywidgets


# to get it running on 3090
# instead first install envs/environment.yaml
# and then `conda install pytorch torchvision cudatoolkit=11 -c pytorch-nightly`
# and then pip install laplace-torch
